name: Deploy Vue.js App to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
         
       
      - name: Google Auth
        uses: google-github-actions/auth@v2
          with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  

      # Step 2: Setup Node.js for Vue app build
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies and build Vue app
      - name: Install Dependencies
        run: |
          cd samey-web-app
          npm install

      - name: Build Vue app
        run: |
          cd samey-web-app
          npm run build

      # Step 4: Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}

      # Step 5: Setup Google Cloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      # Step 6: Configure Docker for Google Cloud
      - name: Configure Docker for Google Cloud
        run: |
          gcloud auth configure-docker

      # Step 7: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/vue-app:${{ github.sha }} .

      # Step 8: Docker Hub Login (optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 9: Push to Google Container Registry
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/vue-app:${{ github.sha }}

      # Step 10: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy vue-app \
            --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/vue-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated